language: python

python:
  - 3.4

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update -qqm
  - sudo apt-get install -qqm wget build-essential python3-dev python-dev
  # install SIP
  - cd /tmp
  #- wget --quiet --output-document=sip.tar.gz http://downloads.sourceforge.net/project/pyqt/sip/sip-4.15.3/sip-4.15.3.tar.gz
  #- tar -xf sip.tar.gz
  #- cd sip-4.15.3
  #- python -B configure.py
  #- make --quiet
  #- sudo make --quiet install
  # install PyQt
  - cd /tmp
  - wget --quiet --output-document=pyqt.tar.gz http://downloads.sourceforge.net/project/pyqt/PyQt5/PyQt-5.3.1/PyQt-gpl-5.3.1.tar.gz
  - tar -xf pyqt.tar.gz
  - cd PyQt-gpl-5.3.1
  - python -B configure.py --confirm-license
  - make --quiet
  - sudo make --quiet install
  - python -c 'import PyQt5, PyQt5.QtGui, PyQt5.QtCore'  # to test if compile its ok
  - cd $TRAVIS_BUILD_DIR

install: true

before_script: rm --recursive --force --verbose *.py[cod]

script: python3 ./linkode-gui.py --tests

after_script: true

after_success: true

after_failure: true

notifications:
  email:
      recipients: JuanCarlosPaco@Gmail.com
      template:
          - "%{repository}@%{branch}: %{message}(%{build_url})"
          - "Build: %{build_number}, SHA: %{commit}, Committer: %{author}, Diff: %{compare_url}"
      on_success: change
      on_failure: always

cache: apt
