language: python

python:
  - 3.4

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update -qqm
  - sudo apt-get install -qqm python3-pyqt5 python3-pyqt5.qsci

install: true

before_script: rm --recursive --force --verbose *.py[cod]

script: python3 ./linkode-gui.py --tests

after_script: true

after_success: true

after_failure: true

notifications:
  email:
      recipients: JuanCarlosPaco@Gmail.com
      template:
          - "%{repository}@%{branch}: %{message}(%{build_url})"
          - "Build: %{build_number}, SHA: %{commit}, Committer: %{author}, Diff: %{compare_url}"
      on_success: change
      on_failure: always

cache: apt
